git clone D:\Documents\PhD\lib\ecma			+lib\+ecma
rmdir +lib\+ecma\.git /S /Q
git clone D:\Documents\PhD\lib\num			+lib\+num
rmdir +lib\+num\.git /S /Q
git clone D:\Documents\PhD\lib\bool			+lib\+bool
rmdir +lib\+bool\.git /S /Q
git clone D:\Documents\PhD\lib\char			+lib\+char
rmdir +lib\+char\.git /S /Q
git clone D:\Documents\PhD\lib\color		+lib\+color
rmdir +lib\+color\.git /S /Q
git clone D:\Documents\PhD\lib\fitting		+lib\+fitting
rmdir +lib\+fitting\.git /S /Q
git clone D:\Documents\PhD\lib\figure		+lib\+figure
rmdir +lib\+figure\.git /S /Q
git clone D:\Documents\PhD\lib\struct 		+lib\+struct
rmdir +lib\+struct\.git /S /Q
git clone D:\Documents\PhD\lib\profile		+lib\+profile
rmdir +lib\+profile\.git /S /Q
git clone D:\Documents\PhD\lib\physics		+lib\+physics
rmdir +lib\+physics\.git /S /Q
git clone D:\Documents\PhD\lib\view\file 	+lib\+view\+file
rmdir +lib\+view\+file\.git /S /Q
git clone D:\Documents\PhD\lib\view\plot 	+lib\+view\+plot
rmdir +lib\+view\+plot\.git /S /Q
git clone D:\Documents\PhD\lib\model\cRAR 	+lib\+model\+cRAR
rmdir +lib\+model\+cRAR\.git /S /Q