function varargout = W0(vm,list,varargin)
lib.module.constraints

% set iteration print function
sPrec	= '%1.12e';
sStrong = ['<strong>' sPrec '</strong>'];
sFormat = strjoin({'%1.3e',sPrec,sPrec,sStrong,'\n'},'\t');
fLog	= @(SOL) fprintf(sFormat,list.chi2(SOL),SOL.data.beta0,SOL.data.theta0,SOL.data.W0);

% set chi2 function
fResponse = @(SOL) list.chi2(SOL);

% set update function
fUpdate = @(x,vm) lib.struct.setfield(vm,...
	'param/W0',		x ...
);

% set model function
fModel = @(SOL) lib.struct.setfield(vm,...
	'param/beta0',		SOL.data.beta0,...
	'param/theta0',		SOL.data.theta0,...
	'param/W0',			SOL.data.W0 ...
);

% set search interval
Xint(1) = vm.param.W0 - 15;
Xint(2) = vm.param.W0 + 15;

% search for solution
[varargout{1:nargout}] = lib.model.tov.rar.gosect(vm,list,...
	'Xint',			Xint,...
	'fResponse',	fResponse,...
	'fModel',		fModel,...
	'fUpdate',		fUpdate,...
	'fLog',			fLog,...
	varargin{:} ...
);
