% load packages
AXIS = lib.require(@lib.model.tov.rar.axes.astro);

% set axes data
AX = {...
	'XLim',		[1E-5,1E4],...
	'XScale',	'log' ...
};

AY = {...
	'YLim',		[1E1,1E15],...
	'YScale',	'log' ...
};

% create axes
ax = lib.module.figure.axes(...
	'x',	AXIS.radius,...
	'y',	AXIS.density,...
	'axes',	[AX,AY] ...
);

% create figure
EXPORT = lib.module.figure.grid(ax);