% load cached data
TBL		= load('+view/+radius_density/CACHE.mat');

% load packages
AXIS	= lib.require(@lib.model.tov.rar.axes.astro);

% load figure
fh		= lib.require(@view.radius_density.figure);

% show figure
figure(fh);

% set plot function for a profile p
fPlot = @(p) lib.view.plot.curve2D(...
	'data', p,...
	'x',	AXIS.radius,...
	'y',	AXIS.density,...
	'plot', {...
		'DisplayName',	lib.sprintf('$\theta_0 = %d$', p.data.theta0) ...
	}...
);

% show RAR solutions (without cutoff)
TBL.profiles.forEach(fPlot);

% show legend
lib.view.plot.legend([],'location','northeast');

% save figure (pdf)
lib.view.file.figure(...
	'figure',	fh,...
	'filepath',	'export/radius-density',...
	'type',		'pdf' ...
);