% find solution (beta0,theta0,W0) for given particle mass m
function varargout = beta0_theta0_W0(vm,list,varargin)
lib.module.constraints

% set iteration print function
sPrec	= '%1.12e';
sStrong = ['<strong>' sPrec '</strong>'];
sFormat = strjoin({sPrec,sStrong,sStrong,sStrong,'%1.3e\n'},'\t');
fLog	= @(SOL) fprintf(sFormat,SOL.data.m/keVcc,SOL.data.beta0,SOL.data.theta0,SOL.data.W0,list.chi2(SOL));

% set vector function 
fVector = @(vm) [
	log(vm.param.beta0)
	vm.param.theta0
	log(vm.param.W0)
];

% set update function
fUpdate = @(b,vm) lib.struct.setfield(vm,...
	'param/beta0',		exp(b(1)),...
	'param/theta0',		b(2),...
	'param/Wp',			exp(b(3)) ...
);

% set model function
fModel = @(SOL) lib.struct.setfield(vm,...
	'param/beta0',		SOL.data.beta0,...
	'param/theta0',		SOL.data.theta0,...
	'param/W0',			SOL.data.W0 ...
);

[varargout{1:nargout}] = lib.model.tov.rar.nlinfit.beta0_theta0_W0(vm,list,...
	'fVector',			fVector,...
	'fUpdate',			fUpdate,...
	'fModel',			fModel,...
	'fLog',				fLog,...
	varargin{:} ...
);