% load packages
AXIS = lib.require(@lib.model.tov.rar.axes.astro);

EXPORT.interp1.radius = @(R) lib.module.ProfileAnchor(...
	@(obj) AXIS.radius.map(obj),...
	@(obj,X) R ...
);

EXPORT.interp1.mass = @(M) lib.module.ProfileAnchor(...
	@(obj) AXIS.mass.map(obj),...
	@(obj,X) M ...
);

EXPORT.interp1.density = @(RHO) lib.module.ProfileAnchor(...
	@(obj) AXIS.density.map(obj),...
	@(obj,X) RHO ...
);

EXPORT.interp1.velocity = @(V) lib.module.ProfileAnchor(...
	@(obj) AXIS.velocity.map(obj),...
	@(obj,X) V ...
);