% load packages
MAP = lib.require(@lib.model.tov.rar.map);

EXPORT.interp1.radius = @(R) lib.module.ProfileAnchor(...
	@(obj) MAP.radius.map(obj),...
	@(obj,X) R ...
);

EXPORT.interp1.mass = @(M) lib.module.ProfileAnchor(...
	@(obj) MAP.mass.map(obj),...
	@(obj,X) M ...
);

EXPORT.interp1.density = @(RHO) lib.module.ProfileAnchor(...
	@(obj) MAP.density.map(obj),...
	@(obj,X) RHO ...
);

EXPORT.interp1.velocity = @(V) lib.module.ProfileAnchor(...
	@(obj) MAP.velocity.map(obj),...
	@(obj,X) V ...
);