lib.module.constraints

% CENTRAL SCALE
EXPORT.density = lib.module.ProfileMapping(...
	@(obj) 1/obj.data.density(1),...
	'\rho_0'...
);

EXPORT.pressure = lib.module.ProfileMapping(...
	@(obj) 1/obj.data.pressure(1),...
	'\rho_0 c^2'...
);

EXPORT.degeneracy = lib.module.ProfileMapping(...
	@(obj) obj.data.theta0,...
	'\theta_0'...
);