lib.module.constraints
ANCH = lib.require(@lib.model.tov.rar.anchor);
MAP  = lib.require(@lib.model.tov.rar.map);

% halo SCALE
fscale = @(obj,ykey) 1/ANCH.velocity_halo.map(obj,ykey);

EXPORT.radius = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.radius),...
	'r_h'...
);

EXPORT.density = lib.module.ProfileMapping(...
	@(obj) fscale(obj,obj.data.density),...
	'\rho_h'...
);

EXPORT.pressure = lib.module.ProfileMapping(...
	@(obj) fscale(obj,obj.data.pressure),...
	'P_h'...
);

EXPORT.mass = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.mass),...
	'M_h'...
);

EXPORT.velocity = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.velocity),...
	'v_h'...
);

EXPORT.potential = lib.module.ProfileMapping(...
	@(obj) fscale(obj,obj.data.potential),...
	'\nu_h'...
);

EXPORT.compactness = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.compactness),...
	'\varphi_h'...
);