lib.module.constraints
ANCH = lib.require(@lib.model.tov.rar.anchor);
MAP  = lib.require(@lib.model.tov.rar.map);

% PLATEAU SCALE
fscale = @(obj,ykey) 1/ANCH.velocity_plateau.map(obj,ykey);

EXPORT.radius = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.radius),...
	'r_p'...
);

EXPORT.density = lib.module.ProfileMapping(...
	@(obj) fscale(obj,obj.data.density),...
	'\rho_p'...
);

EXPORT.pressure = lib.module.ProfileMapping(...
	@(obj) fscale(obj,obj.data.pressure),...
	'P_p'...
);

EXPORT.mass = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.mass),...
	'M_p'...
);

EXPORT.velocity = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.velocity),...
	'v_p'...
);

EXPORT.potential = lib.module.ProfileMapping(...
	@(obj) fscale(obj,obj.data.potential),...
	'\nu_c'...
);

EXPORT.compactness = lib.module.ProfileMapping(...
	@(obj) fscale(obj,MAP.compactness),...
	'\varphi_p'...
);