lib.module.constraints
MAP  = lib.require(@lib.model.tov.rar.map);

% SURFACE SCALE
fScale = @(Y) 1/Y(end);

EXPORT.radius = lib.module.ProfileMapping(...
	@(obj) fScale(MAP.radius.map(obj)),...
	'r_s'...
);

EXPORT.mass = lib.module.ProfileMapping(...
	@(obj) fScale(MAP.mass.map(obj)),...
	'M_s'...
);

EXPORT.velocity = lib.module.ProfileMapping(...
	@(obj) fScale(MAP.velocity.map(obj)),...
	'v_s'...
);